### ISSUE TITLE
Latest update causes build failures

### ISSUE THREAD

**Issue by IDispose** [ma314smith/signedxml#29]
We have renovate bot monitoring updates to our referenced packages. The latest update to this package is adding an indirect reference to `github.com/lestrrat-go/libxml2 v0.0.0-20201123224832-e6d9de61b80d // indirect` and this is causing build failures since we do not have configuration to pull in necessary libraries. 

Was the inclusion intentional? Isn;t this package a pure implementation in `go` to prevent this issue? Any tips on resolving the issue highly appreciated.

**Comment by adamdecaf** [comment]
Yea, we should revert https://github.com/ma314smith/signedxml/pull/27
